### ISSUE TITLE
Sound Settings After Using Fury Mode

### ISSUE THREAD

**Issue by Siniroth1991** [BrightMH/BrightMH#1]
My sound settings will reset to their MAX Values upon LEAVING Fury Mode. Not a major game-breaker, but a bit of an annoyance! :D Happened 3 out of 3 times so far.

~ChronoZero

**Comment by GMCastiel** [comment]
This is a client bug and we plan to fix this in time.

**Comment by MexikanoS** [comment]
https://github.com/BrightMH/BrightMH/issues/20
