### ISSUE TITLE
All mobs have 0 Defense

### ISSUE THREAD

**Issue by forestfishy** [BrightMH/BrightMH#10]
This game is just too easy.
IM not sure if you know or dont know.
But all mobs have 0 def. I Can kill 130lvl mobs even with lvl 24 character (without pots)
![balance](https://cloud.githubusercontent.com/assets/17156817/12942227/927c63b6-cfd9-11e5-926e-5b4033ffe7b2.jpg)

**Comment by GMCastiel** [comment]
Monsters do not have 0 def. There is a factor where the damage you do the exp you gain are decreased by a certain percentage depending on how much higher the monster is. This has not been added yet resulting in what you believe to be the monsters having 0 defense. This will be changed in time. Please remember that this is OBT and everything is subject to change.

Thank you for taking the time to make this bug report.

Kind Regards,
_**_GM@Castiel_*

**Comment by forestfishy** [comment]
Anyway you just repaired that... and u did that game harder :) Thanks for lissteing me
