### ISSUE TITLE
Fury bar

### ISSUE THREAD

**Issue by Pini0** [BrightMH/BrightMH#100]
Had full fury bar - ready to use. Then I left the game. Now the fury bar i fully charged all the time (full blue bar), but I can't use the fury. Nor it decreases, it doesn't even replenish itself when fighting monsters (at first I thought it was just a visual bug). It just stays blue and full. Now it's 3 days like this.

**Comment by MexikanoS** [comment]
What's your character name?

**Comment by Pini0** [comment]
It fixed itself.
