### ISSUE TITLE
plummet monk skill not working

### ISSUE THREAD

**Issue by Xenoh2o** [BrightMH/BrightMH#102]
plummet monk skill called "Sleeping skill" lvl 1 & lvl 2 does not work. i press button and char turns towards mob but does nothing. i tried relog still nothing. this skill is on page 1 of plummet monk skills.

**Comment by VGreport** [comment]
Wrong description/name or wrong effect
use Stunning Skill, works fine :D

**Comment by Xenoh2o** [comment]
i am reporting that a skill does not work. I am not sure what youre trying to tell me VG but here are pics of the broken skill. Also i know stun works :)

![sleep skill1](https://cloud.githubusercontent.com/assets/17970768/14917723/71d4d8de-0dee-11e6-9bcc-658bcd62bd04.PNG)

![sleep skill2](https://cloud.githubusercontent.com/assets/17970768/14917739/810d0b78-0dee-11e6-876e-4b0c70af0e94.PNG)

**Comment by MexikanoS** [comment]
Lawful sleeping skill - works.
Evil sleeping skill - works.

When did the problem occured?
