### ISSUE TITLE
upgrading success lowered?

### ISSUE THREAD

**Issue by Xenoh2o** [BrightMH/BrightMH#104]
seems like upgrading success has been lowered for armor ups. so there are a few variables working. one i was upgrading with my sin not my monk. two i was upgrading 2 patches ago. one thing is for sure and that is now upgrading on monk really sucks! i also had 1 ssc fail which has never happened before, i didnt think they could fail. maybe its back to what the game was originally like but that would also not be good since there are fewer players on the game than the thousands that use to be which means not as many upgrades in game. and yes i know i could farm them. 

for all who read this and cant check to see if upgrade success has actually changed, i.e. coding, i dont need help with solutions or work-arounds or anything for that matter in response to this post here. if you have solutions or comments please find me in game or you could always send me a pigeon, or send me a msg thru forums, thanks!

**Comment by Gr33dyJeW** [comment]
Upgrading with a different class never had any impact on upgrading.
You're just unlucky.
Also upgrade rate is still to high even for a beta testing and it will be lowered for full release.

**Comment by VGreport** [comment]
Its fine, I just did upgrade and it was as usual :P 
It's the same if char with 350 INT (my upgrader)
and a lvl 48 (friend's upgrader) :P I get same result lol
