### ISSUE TITLE
Santa box and others drop only fireworks

### ISSUE THREAD

**Issue by VLEFF** [BrightMH/BrightMH#105]
Every time that i open boxes (all droped by oxes, ice mob, etc), i now get only fireworks.
Is it a bug? Or just like upgrade rate and xp, it is just lowered?

**Comment by VGreport** [comment]
i opened like 200 and had only "2" nice drops (FDD event) lol 80%+ were fireworks
I heard ppl had nice drops from it :( wish I opened it before, didn't know about the further change :/
