### ISSUE TITLE
blood on soulbead

### ISSUE THREAD

**Issue by davelin23** [BrightMH/BrightMH#107]
After putting blood on soulbead there's no indication of bonus amount like birds have it's little mysterious

**Comment by GMCastiel** [comment]
This is something that's always been.

We'll eventually add these things to be thorough.

**Comment by Gr33dyJeW** [comment]
Tae CL soulbead(BI-Gen)  
Tae CL soulbead(BI-Ch)  
Tae CL soulbead(BI-Con)  
Tae CL soulbead(BI-Gh)  
Tae CL soulbead(YI-Gen)  
Tae CL soulbead(YI-Ch)  
Tae CL soulbead(YI-Con)  
Tae CL soulbead(YI-Gh)  
Tae CL soulbead(RI-Gen)  
Tae CL soulbead(RI-Ch)  
Tae CL soulbead(RI-Con)  
Tae CL soulbead(RI-Gh)  
Tae KS soulbead(BJ-Gen)  
Tae KS soulbead(BJ-Ch)  
Tae KS soulbead(BJ-Con)  
Tae KS soulbead(BJ-Gh)  
Tae KS soulbead(YJ-Gen)  
Tae KS soulbead(YJ-Ch)  
Tae KS soulbead(YJ-Con)  
Tae KS soulbead(YJ-Gh)  
Tae KS soulbead(RJ-Gen)  
Tae KS soulbead(RJ-Ch)  
Tae KS soulbead(RJ-Con)  
Tae KS soulbead(RJ-Gh)  
Tae JC soulbead(BC-Gen)  
Tae JC soulbead(BC-Ch)  
Tae JC soulbead(BC-Con)  
Tae JC soulbead(BC-Gh)  
Tae JC soulbead(YC-Gen)  
Tae JC soulbead(YC-Ch)  
Tae JC soulbead(YC-Con)  
Tae JC soulbead(YC-Gh)  
Tae JC soulbead(RC-Gen)  
Tae JC soulbead(RC-Ch)  
Tae JC soulbead(RC-Con)  
Tae JC soulbead(RC-Gh)   

This one is for Tae
ui,dok and wolf follow the same pattern (1st letter reffers to color (B-blue, Y-yellow, R-red),2nd reffers to upgrade level(carps and speedy).
Gen-general - dual rites
Ch-chivalry - tri gifts
Con-continental - quad forms
Gh-ghost - Five ways

All give +10% to base dmg against respective mob type
