### ISSUE TITLE
Please move closer to pick up an item

### ISSUE THREAD

**Issue by Pini0** [BrightMH/BrightMH#108]
Spawned boss with an amulet, 4th one in row (125lvl). The 4th one dropped one up, gold (of course) and 120 set ring. I picked up all of those and could not pick up the 120 set ring, the message said: "Please move closer to pick up an item." I made a 3 screenshots, but all of them got saved fully white.

**Comment by VGreport** [comment]
happened to me that also few times, generally when I don't loot it too quick XD

**Comment by VGreport** [comment]
Did become too common that bug now XD
