### ISSUE TITLE
You went out of the party leader's sight

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#109]
Some times (not too common) it says when u r in a pt o_O
being a steps away even moving the leader too close XD
didn't figure out exactly when it happens :P 
but its solved after u delegate to new leader :D
Just posting to let u know about it :D

**Comment by MexikanoS** [comment]
This is how the game is working. You were getting spammed by such messages 24/7.

Pinned up under enhancement - considering removement of the messages.
