### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by Xenowalker** [BrightMH/BrightMH#111]
1. Master/student: after using "train" function it gave me 12873647362584761847 exp (90% exp) on lvl 136. after relogging it returned to 1%.
2. Brotherhood: after using brotherhood function is propperly shows login/logout but no lvl up of other player.
3. GAK guild: PK function and Robbing fuction not working.

Gaga, witnissed it all, told me to go here :)

**Comment by MexikanoS** [comment]
#111-1. Gotta look into it in a while. #fixed too - thank you.
#111-2. Will be added within next update - thank you.
#111-3. Such functionality was never implemented in original MH, but we'll look into it sooner or later.
