### ISSUE TITLE
Evil glove mage skill

### ISSUE THREAD

**Issue by Xenowalker** [BrightMH/BrightMH#112]
Burning soul skill not debuffing att/def but applying poisen.

bit dubble since main skill also applies poisen but higher poisen dmg, it it has no added value to get this skill.

**Comment by GMCastiel** [comment]
https://github.com/BrightMH/BrightMH/issues/75

**Comment by GMCastiel** [comment]
#75

**Comment by GMCastiel** [comment]
#75 Related issue

**Comment by Xenowalker** [comment]
sry, posted this because it concerns the evil AOE glove skill. it does propperly use AOE (hitting 3 mobs), just not the debuff.

**Comment by GMCastiel** [comment]
That's alright, I just posted the other issue to link them together so we know they're both stemming from the same thing.
