### ISSUE TITLE
Party EXP formula with 8 members

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#115]
##maybe it was like it since before the new exp party formula 
before i only did test with 7 members and did assume the value with 8

Tested new values old ones vs new ones pt of 1,2,3,4,5,6,7,8
100% 125% 110% 95% 80% 65% 50% X
100% 125% 105% 85% 75% 65% 50% 25%

should be increased the value of party of 8  to 35~40%
or to 45% if u change the party of 7 to 55% :P (not important this one ofc lol)
but party of 8 formula is(/was) wrong for sure XD

**Comment by MexikanoS** [comment]
Applied. Thanks.
