### ISSUE TITLE
Pandora dagger and guantlet inventory slots

### ISSUE THREAD

**Issue by Celvation** [BrightMH/BrightMH#122]
![do20160625_2110_1](https://cloud.githubusercontent.com/assets/20117307/16358891/14e327da-3b1a-11e6-9705-b841cf4a23b8.jpg)
![do20160625_2110_2](https://cloud.githubusercontent.com/assets/20117307/16358892/14e39f12-3b1a-11e6-8bd6-91e11299d3fe.jpg)
![do20160625_2110_3](https://cloud.githubusercontent.com/assets/20117307/16358893/14e4afce-3b1a-11e6-94b1-b5c13ee27185.jpg)
![do20160625_2110_4](https://cloud.githubusercontent.com/assets/20117307/16358917/4c8ef358-3b1a-11e6-8674-9e61f8b808f8.jpg)

Pandora dagger use 3 inventory slots instead of 2 and guantlet use 2 slots

**Comment by MexikanoS** [comment]
Will be enhancemented within next update.
