### ISSUE TITLE
Unable to click easily on Mini Monsters(Dragon/B.Ox)

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#126]
Unable to easily click on the next monsters: 
(hard to click and u need use T to target =S)

(13782) "Mini Bonus dragonBonus Monster"
(14814) "Mini B.Ox(40)"
(14815) "Mini B.Ox(45)"
(14816) "Mini B.Ox(50)"
(14817) "Mini B.Ox(55)"
(14818) "Mini B.Ox(60)"
(14819) "Mini B.Ox(65)"
(14820) "Mini B.Ox(70)"
(14821) "Mini B.Ox(75)"
(14822) "Mini B.Ox(80)"
(14823) "Mini B.Ox(85)"
(14824) "Mini B.Ox(90)"
(14825) "Mini B.Ox(95)"
(14826) "Mini B.Ox(100)"
(14827) "Mini B.Ox(105)"
(14828) "Mini B.Ox(110)"
(14829) "Mini B.Ox(115)"
(14830) "Mini B.Ox(120)"
(14831) "Mini B.Ox(125)"
(14832) "Mini B.Ox(130)"
(14833) "Mini B.Ox(135)"
(14834) "Mini B.Ox(140)"
(14835) "Mini B.Ox(145)"
(14836) "Mini B.Ox(150)"
(14837) "Mini B.Ox(155)"

**Comment by Gr33dyJeW** [comment]
Yes, they do have a small hitbox for some reason...
Same goes for bonus 12bf round dragons.
