### ISSUE TITLE
Assassin 144 bow

### ISSUE THREAD

**Issue by Assassin69** [BrightMH/BrightMH#127]
No idea if this is a bug or not as i didnt reach 144 on karma and pandora but been asked to post it.

so the range on bow on 144 ui set is the same as dagger. i thought the whole idea of being a bow was for this. as soon as i take the soulbead and put my bear back on the range is back to normal.

cheers guys.

**Comment by Gr33dyJeW** [comment]
Do you compare range of the same skills while using soulbead and bear or?
Tae/Ui/Dok/Wolk skills have the same range regardless of weapon.
Imagine asassin with wolk skills ranged like bow page 2 skills...
Long story short, range is tied to skills not weapon.
