### ISSUE TITLE
Randomly invisible assassin bug

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#129]
Sometimes assassins are invisible without did use the hide skill O.o
(happened to me two times) use to "see it" constantly during the day
And its not invisible to me, 
cant see the sin from mules and i ask ppl in VV and also cant see the sin

**Comment by Assassin69** [comment]
i seem to get this problem from time to time also. mainly when i go back to VV for a buff.

**Comment by MexikanoS** [comment]
Should be fixed within next update. Thanks for notifying.

#Buffs spawn bug.
