### ISSUE TITLE
Casino isn't stopping the pot/tag/buff timers

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#130]
Only freeze the icons =S, checked many times. 
Used to stop the timers if im not wrong lol...

Always whole Casino was "Neutral Zone"? o.o

EDIT: Ahhh oic :P it's attempt to fix the "cant use buffs/turbo in Casino" ^^,
Just noticed about https://github.com/BrightMH/BrightMH/issues/91 lol :P

**Comment by MexikanoS** [comment]
Martial never stopped timers.

*Working on it.

**Comment by MexikanoS** [comment]
Timers will be stopping within next update.
