### ISSUE TITLE
purple bag drops

### ISSUE THREAD

**Issue by Assassin69** [BrightMH/BrightMH#131]
![do20160901_0130_2](https://cloud.githubusercontent.com/assets/21208446/18151137/c987f5cc-6fe4-11e6-96e5-182c5e4ba7af.jpg)
![do20160901_0130_1](https://cloud.githubusercontent.com/assets/21208446/18151138/ca4a17ce-6fe4-11e6-8034-a402b8c5c4a5.jpg)

**Comment by MexikanoS** [comment]
Thank you for reporting. I'll look into it.

**Comment by Assassin69** [comment]
if i get any more random things from them ill post them up here.

**Comment by MexikanoS** [comment]
Names will be fixed within next update. Thanks for pointing out the bug.
