### ISSUE TITLE
Kiji J wep

### ISSUE THREAD

**Issue by Assassin69** [BrightMH/BrightMH#132]
![kiji j wep](https://cloud.githubusercontent.com/assets/21208446/18233900/ac4c1a82-72ec-11e6-89cd-5c800f36a52d.jpg)
forgot to post this when i got it a while back.

**Comment by VGreport** [comment]
Where did you get the Fire Sword (풍운우 / 281000070)? o_o
and the description should be change to 0 (removed) XD
[It's a commemorative item and the description is useless now, 
even in the KR server that description was removed.]

thought you only can get the trade-able Fire Wooden Sword, 
I remember it was wrongly called Kiji J in another P-servers lol
It should be changed to trade-able aswell =D

**Comment by Assassin69** [comment]
sungwa doungeon. yes it should be tradable :+1:  :)

**Comment by MexikanoS** [comment]
Will be fixed within next update.
