### ISSUE TITLE
Mage's Skill books (not registered ones) for sale

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#133]
NPC N°2380: M.Master NJT (Skill book seller)
He is located in Garden of Heaven

Sells 2 wrong books for mage 
which should be removed from the store:
213620124 Skill book Lv132 lawful mage called O (N°28 in the shop)
223620124 Skill book Lv132 Evil mage called O (N°39 in the shop)

You get this message when you try to use them:
<img src="http://oi68.tinypic.com/2hpku80.jpg" border="0">

**Comment by MexikanoS** [comment]
Will be fixed within next update, thanks for notifying.
