### ISSUE TITLE
teleporting boss 

### ISSUE THREAD

**Issue by seven7brightmh** [BrightMH/BrightMH#135]
walczyłem z bossem w miejscu gdzie stoje, po chwili teleportował sie dalej i combo skille był zablokowane

![image](https://cloud.githubusercontent.com/assets/22467827/18864373/615cbf52-8496-11e6-9abd-b346c14d931e.png)

**Comment by MexikanoS** [comment]
Mobs are warped to their normal area, after moving to far.

The second thing should be already fixed.
