### ISSUE TITLE
Full-screen and resolution issue. 

### ISSUE THREAD

**Issue by xAshaya** [BrightMH/BrightMH#140]
The game refuses to start when full-screen/resolution option is changed, BMH patch needs to be reinstalled to get rid of the error which prevents start. I get the same errors BrightMH #600 but with different messages. Can provide English version of the messages, though it seems those are irrelevant. 
![full-screen_resolution_issue_bmh](https://cloud.githubusercontent.com/assets/22612543/19068591/791e675c-8a23-11e6-950a-85f201249f77.png)

**Comment by MexikanoS** [comment]
From: https://msdn.microsoft.com/en-us/library/ms838282.aspx

Not all privileges referenced are assigned to the caller.
Explanation:
The service was asked to make a set of changes to the privileges in a user account. The requested changes were made for all privileges assigned to the account. One or more of the change requests were for unassigned privileges, so they were not made.

User Action:
This is probably not a problem. Try your privileged operation and see if it fails. If it does, see your administrator for help in obtaining the needed privilege.

**Comment by xAshaya** [comment]
Done with administrator privileges. It resolves the issue, nevertheless it should not create an error in the first place.

**Comment by MexikanoS** [comment]
It has been mentioned, to start the Launcher with the Administrative privileges.
