### ISSUE TITLE
Quest related mobs issue. 

### ISSUE THREAD

**Issue by xAshaya** [BrightMH/BrightMH#141]
![do20161006_0547_1](https://cloud.githubusercontent.com/assets/22612543/19139904/9685e340-8b88-11e6-8ef8-89f52cb66bec.jpg)
![do20161006_0547_2](https://cloud.githubusercontent.com/assets/22612543/19139903/96847622-8b88-11e6-93e3-2f3d19624f19.jpg)
As you can see, in this quest the mobs are not highlighted and are not counted into the quest counter which makes it impossible to finish. Restating the game and quest did not resolve the issue.

**Comment by MexikanoS** [comment]
![np](https://cloud.githubusercontent.com/assets/364289/19152431/36bff226-8bd2-11e6-89ca-528c7520d591.jpg)

Wrong mob.

**Comment by xAshaya** [comment]
Then why name is the same? In old MH there wasn't such issue. Just saying - it's really confusing. 

Anyway, thanks for the help and answer. Appreciate it.

**Comment by MexikanoS** [comment]
It was the same in the old Martial Heroes, trust me. We haven't made any modifications in the mob names, or other things. We're totally basing on the old client from 2010 year.

**Comment by MexikanoS** [comment]
For now, I'll close the topic, but we'll look one day into fixing language strings (especially making quest descriptions more detailed).
