### ISSUE TITLE
Cannot use antidote while having 8 buffs in buff bar (right bar)

### ISSUE THREAD

**Issue by Dual2** [BrightMH/BrightMH#145]
As in title, also on the perm buff bar (one on left) if you have guild buffs and fame pads buffs they overlay and text also overlays.

**Comment by MexikanoS** [comment]
https://github.com/BrightMH/BrightMH/issues/96 Do you own that many buffs?

**Comment by Dual2** [comment]
Well suppose you are boss hunting and you run (hp+), (att+), (def+), (exp+), (drop rate+), (fame+), (class att buff) makes total of seven then if boss stuns you (stun) makes it eight "buff" so using antidote is impossible which makes no sense...
Under normal circumstances nooone would run this many buffs but if someone did his efforts and pots would go in vain ;D

**Comment by Dual2** [comment]
And answering question I might have had something around 15 effects including passives.

**Comment by MexikanoS** [comment]
Patch for such function will be parsed within next server update. Thanks for reporting.
