### ISSUE TITLE
The holes in textures - DL

### ISSUE THREAD

**Issue by Unkas1** [BrightMH/BrightMH#146]
Hello,

please check this out - a few holes in textures in Dead Land.
Holes don't dissapear after relog.

![do20161103_1925_1](https://cloud.githubusercontent.com/assets/23026268/19979873/4daa88ee-a1fc-11e6-9164-4c57b94ddacb.jpg)
![do20161103_1925_2](https://cloud.githubusercontent.com/assets/23026268/19979875/4db1dc2a-a1fc-11e6-9d4f-f2b415866e40.jpg)
![do20161103_1925_3](https://cloud.githubusercontent.com/assets/23026268/19979877/4db2dad0-a1fc-11e6-8ec3-08a32b9d0975.jpg)
![do20161103_1926_1](https://cloud.githubusercontent.com/assets/23026268/19979876/4db27f4a-a1fc-11e6-83d3-2994b69a7b15.jpg)
![do20161103_1926_2](https://cloud.githubusercontent.com/assets/23026268/19979874/4dafd3c6-a1fc-11e6-9a27-8825ef2643bf.jpg)
![do20161103_1927_1](https://cloud.githubusercontent.com/assets/23026268/19979878/4db87288-a1fc-11e6-890b-af136864acb4.jpg)
![do20161103_1927_2](https://cloud.githubusercontent.com/assets/23026268/19979879/4dcb7090-a1fc-11e6-9987-46f81886a5a0.jpg)
![do20161103_1928_1](https://cloud.githubusercontent.com/assets/23026268/19979880/4dd1cb5c-a1fc-11e6-9744-115ba24c845f.jpg)
![do20161103_1928_2](https://cloud.githubusercontent.com/assets/23026268/19979881/4dd359e0-a1fc-11e6-910b-21aea32e904d.jpg)
![do20161103_1928_3](https://cloud.githubusercontent.com/assets/23026268/19979882/4dd59714-a1fc-11e6-8cd2-65b91f29a10b.jpg)

**Comment by Gr33dyJeW** [comment]
Which GPU are you using?

**Comment by Unkas1** [comment]
AMD Radeon (TM) R5M330
Intel(R) HD Graphics 5500
64 bit

**Comment by Gr33dyJeW** [comment]
Well it's definitely a problem on your side.
Integrated GPUs didn't exist at time MH was launched so there are obvious compatibility issues.
Only thing I can suggest is to try and update GPU drivers if you haven't yet.

**Comment by GMCastiel** [comment]
I would also recommend forcing the game to run the Radeon card instead of Intel one.
