### ISSUE TITLE
Lawfull Word quest

### ISSUE THREAD

**Issue by Brainl3ss** [BrightMH/BrightMH#15]
i found a bug in the quest

once you need to teleport to Lucifer Temple that works just fine

then talk kill and talk 2x more you gona be teleported back to Valley Village

then youre not in vv but somewhere underwater where its back and shit and dragged further in 

i just used ma chuck to get back but still

**Comment by GMCastiel** [comment]
Looking into it.

**Comment by GMCastiel** [comment]
Confirmed, will be fixed.

**Comment by MexikanoS** [comment]
Will be fixed within the next server update.
