### ISSUE TITLE
Fame Rang

### ISSUE THREAD

**Issue by Ciri12** [BrightMH/BrightMH#151]
![do20161115_1648_2](https://cloud.githubusercontent.com/assets/23291225/20312352/73da87d4-ab53-11e6-8b7c-1c64866249f2.jpg)
don't have fame to "Hero" and me Nick name don't change.

**Comment by Gr33dyJeW** [comment]
Takes time to refresh fame list

**Comment by MexikanoS** [comment]
Your fame rank depends on other peoples, not on static values anymore.
