### ISSUE TITLE
Skill doesn't work

### ISSUE THREAD

**Issue by Galiusz** [BrightMH/BrightMH#153]
Is it normal that debuffing dehide skill from 2 page for fan(Assymilation energy lvl1) can dehide nobody. Dehide from first page work correct.

**Comment by Galiusz** [comment]
and this skill do nothing

**Comment by Gr33dyJeW** [comment]
Hmmm, yes it looks like lvl 1 skill does nothing. Lvl2 and up are offense skills and they work fine...
