### ISSUE TITLE
Master & Pupil

### ISSUE THREAD

**Issue by DemonIssi** [BrightMH/BrightMH#162]
My master is offline in friends list, But online in master / pupil list.
![do20170122_1733_1](https://cloud.githubusercontent.com/assets/25282454/22183920/232207e4-e0c9-11e6-9c57-604dc2367f0c.jpg)
![do20170122_1733_2](https://cloud.githubusercontent.com/assets/25282454/22183921/25db8e60-e0c9-11e6-82f9-a6537f481a98.jpg)

**Comment by MexikanoS** [comment]
Koreans never implemented 'online-status' for masters.
