### ISSUE TITLE
Character name Fai Lawful to Evil Change no skill points reset

### ISSUE THREAD

**Issue by paysco** [BrightMH/BrightMH#168]
So i recently changed from lawful to evil faction. before i clicked to confirm the change it said that i would reset the 84+ skills, which makes sense because they used to be lawful learned skills. BUT upon conformation of the reset i received no skill points in return. I was just left with what i originally had which was 8 pts. This puts a major damper on my game-play because i am level 120. Please help!

**Comment by paysco** [comment]
So apparently the cure is to use a banno pot to reset skills then buy all the skill books again. fomr the beginning. sounds a little messed up to me because it says only 85+ skills so now ill be down 1500gold to buy every single skill book again. and mhp to buy the banno and jun pot to redo stats to have enough stats to use the books

**Comment by MexikanoS** [comment]
For some reason it was left behind. Already fixed. Thanks for reporting.
