### ISSUE TITLE
crafting issues

### ISSUE THREAD

**Issue by Babix95** [BrightMH/BrightMH#18]
I cant craft any item..
![asdasd](https://cloud.githubusercontent.com/assets/17199237/13009333/261c5342-d19c-11e5-8737-4e76bbec54c5.JPG)

**Comment by GMCastiel** [comment]
This is being looked into right now.

**Comment by Babix95** [comment]
okay :)

**Comment by GMCastiel** [comment]
The crafting seems fine on my end, maybe it was the server locking up.
