### ISSUE TITLE
bug GO price in red/green dragon

### ISSUE THREAD

**Issue by markymoi** [BrightMH/BrightMH#19]
please se this SS. red dragon description is for loots only for 600GO and for green dragon description is loots and pots for you. for 395GO. 

![image](https://cloud.githubusercontent.com/assets/17128167/13009865/295eab24-d1b8-11e5-8bfa-293e934f35b9.png)
![image](https://cloud.githubusercontent.com/assets/17128167/13009873/3d252c82-d1b8-11e5-9e5b-0628754a3b57.png)

**Comment by GMCastiel** [comment]
That's a crappy description from original Pandora, we hope to patch all this in time.

Thanks for the report.
