### ISSUE TITLE
Tiger bug

### ISSUE THREAD

**Issue by chromm91** [BrightMH/BrightMH#29]
WE have a bug with the Tigers in Vv. If i took a with Tiger from the npc i geht a red tiger If i took a yellow Tiger i get a with Tiger. Chromm

**Comment by MexikanoS** [comment]
Korean translation bug. @maybe one day..

**Comment by GMCastiel** [comment]
Yeah, it's not a bug so much as it is lazy botched Korean translations. It'll be fixed, just not this second.

**Comment by MexikanoS** [comment]
@GMCastiel plspls

**Comment by MexikanoS** [comment]
Will be patched within next update.
