### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by frater11** [BrightMH/BrightMH#3]
Can't play the game in the fullscreen mode. The window that appears after launching the game is borderless and covers only part of the screen.

**Comment by GMCastiel** [comment]
This is a client bug and we plan to fix it eventually.

**Comment by marcolem** [comment]
Can you maybe make a resolution from 1920x1080 in the options for full screen?

**Comment by MexikanoS** [comment]
@marcolem : It's not possible from the native developer. Maybe one day, not now.
The same goes for the OP ^

**Comment by MexikanoS** [comment]
Will be available since next patch.
