### ISSUE TITLE
GLT mobs no exp

### ISSUE THREAD

**Issue by Brainl3ss** [BrightMH/BrightMH#30]
![do20160214_1552_1](https://cloud.githubusercontent.com/assets/17193942/13034376/c374929c-d333-11e5-8b68-7584bead95c7.jpg)

im not getting any exp from the mobs in GLT not the 90`s nor the 98`s even with stars

idk if you are aware of this but well here yah go ^^

**Comment by MexikanoS** [comment]
Karma style.
