### ISSUE TITLE
casino bug

### ISSUE THREAD

**Issue by athrun5** [BrightMH/BrightMH#38]
![do20160215_2248_1](https://cloud.githubusercontent.com/assets/17266393/13069169/f858a7ba-d436-11e5-8f0f-18c2c73c4ea8.jpg)

I think the screen shot is self explanatory however I was gambling and I put a bet on the 8x multiplier and it stole my money.

**Comment by MexikanoS** [comment]
Thanks for reporting. Checked, fixed.

**Comment by Se7eNz** [comment]
![image](https://cloud.githubusercontent.com/assets/17140549/13101380/7636646e-d546-11e5-9b06-97e468d272cb.png)
 mee to
