### ISSUE TITLE
Banno quest bug(!)

### ISSUE THREAD

**Issue by Kraljevo94** [BrightMH/BrightMH#40]
After I killed the 100 Y.Y Swordsmen I went to the quad in garden of heaven. Then I talked to quad i noticed that the quest doesn't complete and I could take as many banno's as I want. Please fixeroni.

![do20160217_1829_1](https://cloud.githubusercontent.com/assets/17299320/13118572/25dc7ada-d5a5-11e5-8f9b-3fef868561e0.jpg)
![do20160217_1829_2](https://cloud.githubusercontent.com/assets/17299320/13118573/25df6b14-d5a5-11e5-8fd4-c2c4718a6ac0.jpg)

Screens attached

**Comment by GMCastiel** [comment]
Fixed, thanks for the report!
