### ISSUE TITLE
Exp tag C and Fame tag Icon not dissapearing when ran out.

### ISSUE THREAD

**Issue by Exclusivee** [BrightMH/BrightMH#45]
Hello , this is Exclusive i'm experiencing a bug .
My Exp tag C and Fame tag run out but the icon doesn't dissapear wich makes me unable to start a new xp tag C .
I tryed to relog a few times but then my Xp Tag C and Fame tag just rerolls to 3 minutes , and it runs out again and the icons keep blinking !
I have 2 screenshots , 1st one made 18:01 and 2nd made 18:04

![do20160219_1801_1](https://cloud.githubusercontent.com/assets/17341653/13183013/0677733e-d735-11e5-9408-1da035f9d4da.jpg)
![do20160219_1805_1](https://cloud.githubusercontent.com/assets/17341653/13183016/0a7cc10a-d735-11e5-8969-f065c6e60236.jpg)

Greetings,
Exclusive

**Comment by GMCastiel** [comment]
Sounds like the tag hasn't actually run out yet in this instance, and the timer is just being wonky.
