### ISSUE TITLE
Bug when fury close. lvl back to 0 and 1

### ISSUE THREAD

**Issue by hieucamdo** [BrightMH/BrightMH#47]
I got this bug 2 time when my fury going to full.
lvl still 123 but character infor back to lvl 0
Cant use pot and other itmes

![do20160221_1231_1](https://cloud.githubusercontent.com/assets/17266265/13201298/ebaaa90e-d89c-11e5-9a44-ed45dd19a800.jpg)

**Comment by MexikanoS** [comment]
Haven't seen it at any other player.. Haven't seen it on my own, I guess it was just a one time bug, caused by latest update on march.
