### ISSUE TITLE
Nanoo's buglist #2

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#48]
- Chat bug still active (fixed when I press "CRTL)
- You get Kao during guild war
- Iam 144 and still people stun me non stop during guild war
- tons of green crits against people during war
- you can cast skills during budong loading and it does not break the acutal budong 
-> so you are able to kite and cast budong with full DMG
- Iam 144 and I do like 7k crits on 132 players which is way too much 
-> I was not on any kind of pots during guild war though
- Imoogi doesnt drop anything
- fury should be at 0 when you relog 
- you get tons of fame from LT monsters if you get a star, though you are way higher

**Comment by MexikanoS** [comment]
Chat bug is a chat bug, I'll work something out on it soon.
