### ISSUE TITLE
Market  Go's

### ISSUE THREAD

**Issue by LimoNEt** [BrightMH/BrightMH#5]
I have problem buy mhp

http://zapodaj.net/efda897fa4255.png.html

**Comment by MexikanoS** [comment]
You gotta go to the shop through website, on the navigation panel press "Donation". We're planning to fix the button URL on the next update.

**Comment by GMCastiel** [comment]
Will be fixed on next update.

**Comment by GMCastiel** [comment]
Fixed on server start.
