### ISSUE TITLE
hide for monk ? ^^

### ISSUE THREAD

**Issue by Se7eNz** [BrightMH/BrightMH#51]
![image](https://cloud.githubusercontent.com/assets/17140549/13279633/87c1552a-dad9-11e5-8113-63a44a868461.png)

**Comment by clearnote7** [comment]
There is hide potion in game lol

**Comment by Se7eNz** [comment]
i know, they don't use this pot

**Comment by MexikanoS** [comment]
#em shitty synchro @ fixed
