### ISSUE TITLE
GUILD

### ISSUE THREAD

**Issue by Brainl3ss** [BrightMH/BrightMH#54]
when creating a new guild the one who creates can see that its a MUN guild but the one who is with you or standing in the same area as you does see the guild name and ur name but not if it is MUN PA GYO or anything

![a0d659bfd2aeaac980fd1204f29339fe18389d7aa68673b0a1 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/17193942/13349114/27f8b67e-dc78-11e5-817e-0fbff44468a0.jpg)

**Comment by MexikanoS** [comment]
Thanks to the koreans, the extGuildPacket isn't working as it should without reinitialized character. So I've added reinitialization, thank you and regards. #fixed
