### ISSUE TITLE
Quest problem

### ISSUE THREAD

**Issue by darkfusion69** [BrightMH/BrightMH#55]
HI ! I made an alt to help GaGa to find quests that are bugged. 

The quest lvl 2-7 "Attend Gathering to hunt foxes" seems bugged. 

We must kill demon foxes but there is no demon fox in plane of vv.

(Quest took in plane)

**Comment by FrenchManiaks** [comment]
More information :

-Quest "Find Clothing's materials" don't have the little Markers on the quest mobs that we need to kill (Wolfs)

-Quest "W.WangQiang's wedding ceremony" need to skill 30 Sly nine, they don't exist. (Quest lvl 10-17)

-Even if I'm a monk the quest lvl (12-35) for sin, war and Mage are showing available in "ALL QUEST" but I can't take them. Relog can't fix this.

-The quest "Search for pedlar Baekwon's C.I (19-22)" is showed available in ALL QUEST but impossible to take it. Same for the quest "Kill a trator (19-22)", "A Bear in Green Valley(19-22)"

-At quest "Driving out the Chief miners(30-35)" it says to kill Chief miners but we need to kill Miners only to finish the quest.

-GMH@FRManiaK

**Comment by MexikanoS** [comment]
Language fixes. @GMCastiel plspls
