### ISSUE TITLE
Problem with critics

### ISSUE THREAD

**Issue by Table678** [BrightMH/BrightMH#56]
I have maksimum lvl of passive Atk succes rate, critical succes rate(19%). Since 2 days i had 0 green critics. It looks like passive doesn't work. Also my friend have build with critics and pot for critics and he has the same bug.

**Comment by MexikanoS** [comment]
Okie, server version of crits, won't be modified anymore, so this one goes into wontfix & close. Thanks for notifying anyway, as it been open for a few months.

**Comment by Gr33dyJeW** [comment]
Crit rate never had any connection with green crits (only white). Closed
