### ISSUE TITLE
Boss 91 AT2

### ISSUE THREAD

**Issue by logaanx** [BrightMH/BrightMH#59]
Hello,
I got server disconnected each time  I kill the boss at the end of AT2.
It happened also to another .

**Comment by GMCastiel** [comment]
Are you referring to the Warrior Monster boss?

**Comment by logaanx** [comment]
Yes, Warrior Monster. Just killed and d/c 2.16 am

**Comment by MexikanoS** [comment]
Will be fixed with next update.
