### ISSUE TITLE
Evil word quest bug

### ISSUE THREAD

**Issue by Table678** [BrightMH/BrightMH#60]
I have 146 lvl and i want open Muhyulbaekmi word(evil word). On this letter write that this quest is 36-160 evil. I'm evil and i can't open it. It shows "Your level is higher than the required level".

**Comment by MexikanoS** [comment]
You're not able to start several quests after 144 lvl. It's client sided, and we'll look into it soon.

**Comment by Table678** [comment]
thanks for answer

**Comment by MexikanoS** [comment]
Will be fixed within the next server update.
