### ISSUE TITLE
Four Hearts Quest

### ISSUE THREAD

**Issue by darkfusion69** [BrightMH/BrightMH#61]
When you take the Four Heart quest (Dropped from a mob in sz) everything works fine until you finished it. When finished you can of course choose your reward and after choosing the reward the quest don't end, it stays in "Quest ON" with "Progress" at 100%. The NPC got his yellow icon on his head but when I go to talk to him nothing happens. So dupe is impossible I think.

**Comment by MexikanoS** [comment]
Will be fixed on next update
