### ISSUE TITLE
Vending disables Prt Scr button

### ISSUE THREAD

**Issue by MexikanoS** [BrightMH/BrightMH#62]
As in the title

**Comment by VGreport** [comment]
You can print if you click in any chatbox and press ENTER or if you press ESC

Something weird happens there lol coz another keys work fine
like "Y"(switch jacket/pants) "U"(switch cape/shoes) "E"(switch inventory page)

**Comment by MexikanoS** [comment]
Will be fixed within next update. #SS sytem has been rewritten.
