### ISSUE TITLE
Fame from fame mobs is rolling back

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#68]
In the previous 3hrs I did the 10 *3 fame mobs at VGassassin 
then when it reclogged to do it at VGwarrior noticed they had the same Fame lol... 
then I killed one more to test in the same char..

Before kill it:
<img src="http://oi68.tinypic.com/24e51jb.jpg">

Right after killed it:
<img src="http://oi63.tinypic.com/fw1s8x.jpg">

After relog and teleport to OC lol:
<img src="http://oi67.tinypic.com/xpx547.jpg">

**Comment by MexikanoS** [comment]
Will be patched on next server patch.
