### ISSUE TITLE
BF

### ISSUE THREAD

**Issue by LimoNEt** [BrightMH/BrightMH#7]
I have problem start

http://zapodaj.net/de726d0847dcb.png.html

**Comment by GMCastiel** [comment]
Could you explain? In Polish is fine.

**Comment by LimoNEt** [comment]
Czasami gdy wchodzę na BF po przez bilet nie mogę rozpocząć gry na arenie. Miałem tak 2 razy i czekałem do samego końca aby mnie przeniosło do vv ale kolejnym razem już było dobrze.

**Comment by clearnote7** [comment]
I have this bug too, it seems reproducible if you TP to 12BF a little late, the camera just pans around non stop and you can't move your character

**Comment by GMCastiel** [comment]
Confirmed, will be fixed.
