### ISSUE TITLE
Kiji C Jacket (K) Manual

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#71]
Hey there,

well all ingredients are based on Gumdan except Kiji C Jacket (K) manual.

The manual needs 5 Humanmopis, those are basically Tiger skin but they still do not work in the manual. Eighter it has to be changed into Tiger Skin or to Gumdan.

**Comment by VGreport** [comment]
Yeah fix it please I cant make mine as well :/

**Comment by MexikanoS** [comment]
Will be "fixed" on next client patch.
