### ISSUE TITLE
Fame mob with no fame

### ISSUE THREAD

**Issue by Table678** [BrightMH/BrightMH#74]
Fame mob lvl 125 in front of Shadow temple don't give fame.
That niga
![fame](https://cloud.githubusercontent.com/assets/17674529/14080925/2d421dd4-f508-11e5-9036-2b37c53b219c.png)

**Comment by GMCastiel** [comment]
That's because he's fake af.

**Comment by MexikanoS** [comment]
Yeah, but he did gave fame :p Will be fixed on next server update.
