### ISSUE TITLE
fist mage page 2 offense/defense debuff skill not working

### ISSUE THREAD

**Issue by Xenoh2o** [BrightMH/BrightMH#75]
as title says this skill isnt working. it only hits 1 mob not 4 and it does not debuff as it says at all

**Comment by MexikanoS** [comment]
Could you tell us the name of the skill?

**Comment by Xenoh2o** [comment]
sorry for late reply name of skill is : Guard Palm (lawful name)

**Comment by MexikanoS** [comment]
![rs](https://cloud.githubusercontent.com/assets/364289/14380108/2590f046-fd7e-11e5-9c2c-20ead6d71e5a.png)

Skill works as it should. Or do you mean any other level than 1?

**Comment by Xenoh2o** [comment]
its supposed to debuff defense and offense of target it doesnt do that and yes i mean the whole skill tree for that skill lvls 5,4,3,2. Also this pic just shows aoe did you check to see if it does debuff?

**Comment by Xenoh2o** [comment]
i tested the lvl 1 guard palm and it does not debuff mobs at all

**Comment by Xenoh2o** [comment]
is this working yet?

**Comment by GMCastiel** [comment]
This'll be fixed in the future. We'll need to figure out all the different skills that should always cast a buff/debuff and apply the correct effects to them.
