### ISSUE TITLE
Dropped "Event"item is non-pickable by yourself when being in party

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#76]
Around 4am after farm with VGwarrior around 2hrs I found a SZ 3days ticket

then I get to the next spawn with VGassassin, and did party lol then being in different spawn
an Ox after 2-3hrs more dropped a SZ 3days ticket to VGassassin but it was non-pickable
when the character killed the Mini Ox itself :S 

then ran with VGwarrior to check if he can but nah aswell lol 
(idk if that about not be able to pick up by another person the event items is normal)

After 6hrs+ more I tried to farm another SZ 3days ticket with VGassassin for party in SZ
and nothing I farmed until the GM buff of this afternoon ;/  When the char dropped one but it happened

Confirmed it was not random success coz being in a party after the GM buff event with dif char
one SZ 3days ticket was dropped (never saw one when lvling lol) then that happened also

**Comment by MexikanoS** [comment]
Thx, will be fixed within next server update.
