### ISSUE TITLE
Buffs/Debuffs

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#78]
When you have more than 8 Buff/Debuffs on yourself you are not able to gain more buffs like hide/HP into MP because debuffs takes over that slot till it expires.

I tried my best but Antitode somehow doesnt work aswell to delete the debuffs (which should not be a factor anyways) which means you have to wait till those debuffs expire and have less than 8 slots to buff yourself.

**Comment by MexikanoS** [comment]
Buffs are buffs - it doesn't matter if it's warfare buff, of normal buff. Their limit is 18 and I guess that you've all slots taken :p

**Comment by WornisOG** [comment]
Well I figured that out yesterday with GreedyJew which leads to another problem.

When ever you are debuffed - antitode somehow does not work - atleast 2 days ago.

**Comment by Gr33dyJeW** [comment]
Define "debuffed"

**Comment by WornisOG** [comment]
Well I know that you cannot debuff the illusion bullet debuff.

You actually should be able to delete the HP loss per second poison with antitode water.
Sometimes it works but after some time you are not able to delete that poison and some strange korean texture pops in the left corner.
