### ISSUE TITLE
Casino

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#79]
When every you did a mistake on casino bets you are not able to cancel them anymore.
With or withou tickets.

**Comment by MexikanoS** [comment]
Thanks for notifying, will be fixed within next server patch.

**Comment by WornisOG** [comment]
Well it is "fixed" in a way but you only delete in 1g steps instead of what you actualy took to bet.
I just bet 40g and it took my 40 clicks to remove it.
