### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#8]
Well I ve been experincing strange chat bug.

When ever I type "v" - I get the whole last sentences back instead of "v".
When I type "e" - the whole sentences gets deleted when Iam whsipering.
Sometimes when I wasnt to delete a letter the whole word dissapears.
When ever you tab out - you automaticly get a disconnect.
Iam not sure if its wanted - but Ive been able to do BF solo with crappy gear and not on warfare pots
(Bosses/Seals are way too easy to kill in my opinion)
Sound gets resetted when you use fury.
You dont get any Ingwe nor fame from after match dragons.
After BF your actual place does not get saved -> you spawn in VV.
You have no time after the dragons dissapear to pick up stuff.
BF seems to be delayed - instead of 5 minutes its like 10.
BF used to be 12 rounds at around 20 CEST.
Not quiet sure if Revenge Battle has been implented (17 / 22 CEST).
Friendslist gets removed everytime (after a certain amount of time).
Sometimes bosses / monsters are stuck in one place.
You dont lose 2% when you die.
Since I skilled the level 96 crit rate passive of Assassin - I dont do any white crits anymore.
Stars only give 20x EXP instead of 40x.
Party does not get destroyed when you switch to another place.
-> e.g Ochun to VV, BF 
Money does not get divided into two when you are in a party.
Starter EXP tag gives 100% more EXP instead of 30%.
Any kind of boss in RC does not give fame.
Lawful Dagger Skill level 87 "Shield Defemce" does not stun.
RC bosses do not give the right amount of gold and fame, no single drop aswell.
Imoogie does not give any kind of drop.

**Comment by GMCastiel** [comment]
Confirmed, will be fixed.

**Comment by WornisOG** [comment]
Bring up my post.

96 crit rate passive skill should be fixed soon as possible.
