### ISSUE TITLE
Assassin skill does not sleep/stun mobs

### ISSUE THREAD

**Issue by Xenoh2o** [BrightMH/BrightMH#80]
Assassin lawful skill named Flying Dagger is a sleep/stun skill at levels 102, 117, and 132. This skill at lvl 87 is the dagger assassin page 2 hiding skill and I think it works (mobs can see me tho and not sure if they are supposed to or not). Flying dagger does damage to mobs but they dont go to sleep/become stunned.

**Comment by GMCastiel** [comment]
Freeze skills won't always freeze the target. It's always been a chance to freeze, not a guarantee.
