### ISSUE TITLE
Ui J 

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#82]
Well we had the following problem:

Hokoshiro wanted to change his Ui J +5 itmes (A) into (W). He is a warrior and couldnt change the items into warrior though he had Taesungstones. I could change them into warrior somehow, Iam an assassin.

The weird thing is that he could change a Ui J +0 Plummet into a Lance.

**Comment by MexikanoS** [comment]
You have at least 3 different types of Taestones in the game - the stackable ones, are the right ones. Looks like Hokoshiro did used the different ones, that aren't client scripted.

**Comment by MexikanoS** [comment]
Yeah, someone spawned wrong items. That's it.
