### ISSUE TITLE
12 Rare_Manual_W_Box  (36-160)

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#86]
Kiji manual of 1day show wrong item description (Real kijis)
Old visual bug =P but reporting since I was told to do it XD

**Comment by MexikanoS** [comment]
There are two manuals.. It has been said thousand times.

**Comment by VGreport** [comment]
Yeah there are 2 manuals 
but 1 day lv36 manuals should show lv36 1d weapons :D instead show perm lv74 in the manufacture options D;

**Comment by VGreport** [comment]
Added fix for it  on my <a href="http://brightmh.com/thread-741.html" target="_blank">Manual Patch</a> and my <a href="http://brightmh.com/thread-57.html" target="_blank">Full Client</a>

**Comment by VGreport** [comment]
The file alone with only it fixed (products.scr)
<a href="https://goo.gl/oCHq7H" target="_blank">goo.gl/oCHq7H</a>

**Comment by MexikanoS** [comment]
Patch will be parsed within next server update. Thanks for reporting and helping with fix.
