### ISSUE TITLE
Combo skill bug

### ISSUE THREAD

**Issue by VGreport** [BrightMH/BrightMH#87]
Well its very old bug XD and also i was told to report it :3
It don't let you load new combos, specially happens when u use  over 1 combo
Only you get rid of it when u re-log, die or teleport

**Comment by MexikanoS** [comment]
Could you please tell me, what skills are there on your combo list?

**Comment by VGreport** [comment]
Happens with every attack combo / every class/weapon lol and to everybody 
(at least everybody who I did party)

even with buffs in monk (only 2 skills in combo) [rarely happens in it XD like once a day :D]
in each party I did at least each 20min someone have to re-log due to it :p

not complaining ^^ IMO it's ok =p it's part of everyday =) its since server was open =) [OBT]
