### ISSUE TITLE
Creating S-quad form tablet in V.V designer

### ISSUE THREAD

**Issue by rahail** [BrightMH/BrightMH#88]
I tried to place one 120 quad form tablet. It says "failed" then both manual and tab gone. In like less than 1 minute, it lagged. then pots not functioning, so I relogged and when I'm back, both the manual and tab are back. This all happened in V.V.

**Comment by Gr33dyJeW** [comment]
You need 4 same tablets to make S

**Comment by rahail** [comment]
Yeah I know. But the lost items part and the not functioning screen was my report. Cause we could have just have a notification about the invalid number of tabs or wrong tabs when "Produce" is clicked.

**Comment by MexikanoS** [comment]
Will be fixed with next server patch. Thank you for notifying.

**Comment by rahail** [comment]
cool. thanks
