### ISSUE TITLE
Turbo/casino

### ISSUE THREAD

**Issue by davelin23** [BrightMH/BrightMH#91]
If you login in casino you can't activate turbo in casino

**Comment by Gr33dyJeW** [comment]
Yea, you can't use skills in casino.

**Comment by GMCastiel** [comment]
Like Gr33dyJeW said, this was a by-product of the intended feature of skills not being usable in the casino. That said, it doesn't mean it has to be that way forever.

**Comment by MexikanoS** [comment]
Will be fixed within next update.
