### ISSUE TITLE
Cant use skills with 1d / 7d kiji dagger 

### ISSUE THREAD

**Issue by BigBearr** [BrightMH/BrightMH#94]
as the title says.
In this SS you can see the orange message which came while trying to cast any skill:
![do20160423_0435_1](https://cloud.githubusercontent.com/assets/18624295/14758861/7f09abe6-090d-11e6-9587-bbf42d43b9a7.jpg)

**Comment by MexikanoS** [comment]
It's not dagger. The equipped weapon is gauntlet.
