### ISSUE TITLE
Gak Guilds

### ISSUE THREAD

**Issue by TheLastNinja** [BrightMH/BrightMH#95]
The Forums Guild requirements says Only evil players can create these, but i've created 1 with a lawful player, even recruited other lawful players as well.

**Comment by Gr33dyJeW** [comment]
GAK guild functionality was never fully implemented even on official server.
Only thing I remember specifical about GAK guild is that members had their name hidden to all those not in guild (e.g. *********)

**Comment by GMCastiel** [comment]
This is something we could look into doing. It may not have been functional on the official servers, but that doesn't mean it can't be functional here as well.

**Comment by Gr33dyJeW** [comment]
Main function which was never realised is like this:
GAK guild can put KOS (kills on sight) on any player by its name (regardless of its guild) and kill it like it has KAO for certain amout of gold. Idea is for certain players to pay GAK guild for asassinations.
My thinking is this would cause too much griefing...
Think about it.

**Comment by MexikanoS** [comment]
Already implemented on Korean Version of the game. #wontfix
