### ISSUE TITLE
Can not Get hide Buff

### ISSUE THREAD

**Issue by i3u5hy** [BrightMH/BrightMH#96]
Ok so When i have this many Buffs on Sin if i use Hide skill i do not hide at all ... if i get casino buffs before the hid buffs Crit ones and stuff i dont get the Crit buffs with hide and so on... it seem the max i can have at once is 6 in total... Other say they can get up to 10

a pic of the current buffs i have
[http://puu.sh/owi5Z/66586b8444.jpg](url)

**Comment by MexikanoS** [comment]
The total possible amount of buffs is 18. You can't get over it.
