### ISSUE TITLE
Quest xp reward

### ISSUE THREAD

**Issue by VLEFF** [BrightMH/BrightMH#99]
It's been two quest that it says that i have gained xx amount of xp, but I actually earned nothing.
It happened after yesterday's patch, maybe is it related?

The two quests are : 
- Anicient Tomb lvl 2 : Capture the Killer   (LVL 83~85)
- Tibet : Kill the hired warriors of S.T! ( LVL 85~87)

I also noticed a drop of xp gained by killing monsters since yesterday's patch.
I used to earn ~390 000 000 000 from lvl 134 worms, now i earn ~220 000 000 000 (with exactly same xp buff)
Is that normal?

**Comment by MexikanoS** [comment]
First thing will be fixed within the next server update.

Second thing - we're slowly forcing the server to go into stable. Exp will be lowered part by part.
